
# anti_ex17_1_reverse
# ex17_1, left, gene is reverse strand, left out;
# ex17_1_reverse means "right out" to connect others;
# then, choose right side base
selected_str = "GATCGAATTCTCACTCTCACAACCAATGAG"
joint_direction = "right"
spanned_length = 40

###
file_path=r'/scratch/chanc3/FFPE-result-10-2019/Chang_Run2_10_08_2019/Untitled_from_191004_A00870_0031_AHGHH7DRXX-142192051/FASTQ_Generation_2019-10-05_18_33_42Z-193788624/extract_fastq/1195/1195_anti_ex17_1_reverse_R1_only_read_base-for_Clustal.txt'

###
myfile = open(file_path)

###
x = []
i = 1
try:
    for line in myfile:
        if i%2==0:
            print(line)
            print(line.find(selected_str))
            if joint_direction=="right": 
                print(line[line.find(selected_str) + len(selected_str):line.find(selected_str) + len(selected_str) + spanned_length])
                x.append(line[line.find(selected_str) + len(selected_str):line.find(selected_str) + len(selected_str) + spanned_length])
        i+=1
finally:
    myfile.close()

###
from collections import Counter
c=Counter(x)


##### 30 bases

Counter({'GAATACTTGGACCTCAGCCAACCTCTCGAA': 113, 'AAAAAAAATGGATAAGCAAGTTAAGGAAGT': 48, 'GTAAGAACTTCCTTTTAGAAGCCCCTTGTC': 31, 'AGAGAGGCTGCTCACCCAACAGACGTCTCC': 26, 'GAATACTTGGACCTCAGTCAGCCTCTCGA\n': 8, 'AGAGAGG\n': 7, 'AAAAAA\n': 7, 'ATGCCATCTTCCTATTTAATTGAACTCCAT': 6, 'GAATATTTGGACCTCAGCCAACCTCTCGAA': 6, 'AGAGAGGCTGCTCACCCA\n': 6, 'GAATACTTGGACCTCAGCTAACCTCTCGAA': 5, 'AGAGAGGCTGCTCACCC\n': 5, 'AGAGAGGCTGCTCACCCAACAG\n': 5, 'AGAGAGGCTGCTCACCCG\n': 4, 'AGAGAGGCTGCTCAC\n': 4, 'GAATACTTGGACCTCAGCCAACC\n': 4, 'AAAAAAAATGGATAAGCA\n': 3, 'AGAGAGGCTGCTC\n': 3, 'GTAAGAACTTCCTTTTAGAAGCCCC\n': 3, 'AGAGAGGCTGCTCACCCAAC\n': 3, 'GTAAGAACTTCCTTTTAG\n': 3, 'ATTCCACAGAGAGAGGCTG\n': 3, 'AAAAAAAATGGATAAGCAAGTCAAGGAAGT': 2, 'GAAT\n': 2, 'GAATACTTGGACCTCAGCCAACCTCTCG\n': 2, 'GTAAGAACTTCCTTTTAGAAGC\n': 2, 'CTACTTCCTGAGAAGTTCCCCCATGACAAG': 2, 'GAATACTTGGACCTCAGCCAACCTCGAACA': 2, 'AAAAAAATGGATAAGCAAGTTAAGGAAGTG': 2, 'GACAGCAAAATCCAGGCTTAGGATGCGACG': 1, 'GAATACTTGGACCTCAGCCAACCCCTCGC\n': 1, 'AGAGAGGCTGCTCACCCAACAGACG\n': 1, 'AAAAAAAATGG\n': 1, 'AAAAAAAAT\n': 1, 'GAATACTTGACCTCAGCCAACCTCTCGAAC': 1, 'AAAAAAAATGGAT\n': 1, 'AAAAAAAATGGATAAGCAAGTTAAGGA\n': 1, 'GAAAACTTGGACCTCAGCCAACCTCTCGAA': 1, 'TCCTGCTATGAAGGTCTGAGC\n': 1, 'CAAAGGAG\n': 1, 'TCCTGCTATGAAGGTCTGATC\n': 1})

##### 20 bases
Counter({'GAATACTTGGACCTCAGCCA': 122, 'AAAAAAAATGGATAAGCAAG': 51, 'GTAAGAACTTCCTTTTAGAA': 36, 'AGAGAGGCTGCTCACCCAAC': 35, 'GAATACTTGGACCTCAGTCA': 8, 'AGAGAGG\n': 7, 'AAAAAA\n': 7, 'ATGCCATCTTCCTATTTAAT': 6, 'GAATATTTGGACCTCAGCCA': 6, 'AGAGAGGCTGCTCACCCA\n': 6, 'GAATACTTGGACCTCAGCTA': 5, 'AGAGAGGCTGCTCACCC\n': 5, 'AGAGAGGCTGCTCACCCG\n': 4, 'AGAGAGGCTGCTCAC\n': 4, 'AAAAAAAATGGATAAGCA\n': 3, 'AGAGAGGCTGCTC\n': 3, 'GTAAGAACTTCCTTTTAG\n': 3, 'ATTCCACAGAGAGAGGCTG\n': 3, 'GAAT\n': 2, 'CTACTTCCTGAGAAGTTCCC': 2, 'AAAAAAATGGATAAGCAAGT': 2, 'GACAGCAAAATCCAGGCTTA': 1, 'AAAAAAAATGG\n': 1, 'AAAAAAAAT\n': 1, 'GAATACTTGACCTCAGCCAA': 1, 'AAAAAAAATGGAT\n': 1, 'GAAAACTTGGACCTCAGCCA': 1, 'TCCTGCTATGAAGGTCTGAG': 1, 'CAAAGGAG\n': 1, 'TCCTGCTATGAAGGTCTGAT': 1})

##### 40 bases
Counter({'GAATACTTGGACCTCAGCCAACCTCTCGAACAGTATTCAC': 111, 'AAAAAAAATGGATAAGCAAGTTAAGGAAGTGAAGAGCAGA': 47, 'GTAAGAACTTCCTTTTAGAAGCCCCTTGTCCTTGGTTGTC': 30, 'AGAGAGGCTGCTCACCCAACAGACGTCTCCATCTCCAAAA': 26, 'GAATACTTGGACCTCAGTCAGCCTCTCGA\n': 8, 'AGAGAGG\n': 7, 'AAAAAA\n': 7, 'ATGCCATCTTCCTATTTAATTGAACTCCATTGTCAGAGAC': 6, 'GAATATTTGGACCTCAGCCAACCTCTCGAACAGTATTCAC': 6, 'AGAGAGGCTGCTCACCCA\n': 6, 'GAATACTTGGACCTCAGCTAACCTCTCGAACAGTATTCAC': 5, 'AGAGAGGCTGCTCACCC\n': 5, 'AGAGAGGCTGCTCACCCAACAG\n': 5, 'AGAGAGGCTGCTCACCCG\n': 4, 'AGAGAGGCTGCTCAC\n': 4, 'GAATACTTGGACCTCAGCCAACC\n': 4, 'AAAAAAAATGGATAAGCA\n': 3, 'AGAGAGGCTGCTC\n': 3, 'GTAAGAACTTCCTTTTAGAAGCCCC\n': 3, 'AGAGAGGCTGCTCACCCAAC\n': 3, 'GTAAGAACTTCCTTTTAG\n': 3, 'ATTCCACAGAGAGAGGCTG\n': 3, 'AAAAAAAATGGATAAGCAAGTCAAGGAAGTGAAGAGCAGA': 2, 'GAAT\n': 2, 'GAATACTTGGACCTCAGCCAACCTCTCGAACAGTATTTAC': 2, 'GAATACTTGGACCTCAGCCAACCTCTCG\n': 2, 'GTAAGAACTTCCTTTTAGAAGC\n': 2, 'CTACTTCCTGAGAAGTTCCCCCATGACAAGCAGAACTGTG': 2, 'GAATACTTGGACCTCAGCCAACCTCGAACAGTATTCACCT': 2, 'AAAAAAATGGATAAGCAAGTTAAGGAAGTGAAGAGCAGAG': 2, 'GACAGCAAAATCCAGGCTTAGGATGCGACGATGCTTACAT': 1, 'GAATACTTGGACCTCAGCCAACCCCTCGC\n': 1, 'AAAAAAAATGGATAAGCAAGTTAAGGAAGTGAAG\n': 1, 'AGAGAGGCTGCTCACCCAACAGACG\n': 1, 'AAAAAAAATGG\n': 1, 'GTAAGAACTTCCTTTTAGAAGCCCCTTGTCCGTGGTTGTC': 1, 'AAAAAAAAT\n': 1, 'GAATACTTGACCTCAGCCAACCTCTCGAACAGTATTCACC': 1, 'AAAAAAAATGGAT\n': 1, 'AAAAAAAATGGATAAGCAAGTTAAGGA\n': 1, 'GAAAACTTGGACCTCAGCCAACCTCTCGAACAGTATTCAC': 1, 'TCCTGCTATGAAGGTCTGAGC\n': 1, 'CAAAGGAG\n': 1, 'TCCTGCTATGAAGGTCTGATC\n': 1})
